apiVersion: apps/v1
kind: Deployment
metadata:
  name: "narky-blog-io"
  namespace: default
  labels:
    app: narky-blog-io
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: narky-blog-io
  template:
    metadata:
      labels:
        app: narky-blog-io
        commit: "${COMMIT}"
    spec:
      containers:
        - name: narky-blog-io
          image: "${IMAGE}"
          ports:
            - containerPort: 3000
          command: ["lein", "with-profile", "-dev,+stubs", "trampoline", "run"]
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: 600Mi
              cpu: 20m
            limits:
              memory: 700Mi
              cpu: 1000m
      imagePullSecrets:
        - name: regcred