name: Branch Tests
on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.2'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          lein: "2.9.1"
      - name: Install dependencies
        run: lein deps
      - name: Run tests
        run: lein test
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: ${{ github.workflow }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
